### ISSUE TITLE
The makefile is missing the -fopenmp C flag and thus the related pragmas are ignored by the compiler.

### ISSUE THREAD

**Issue by JulianMarcusSchroeder** [silver-ymz/bench2#1]
I played with the code here since these was a concern with  -mcpu=neoverse-v1 versus -march=armv8-a+sve flags.
With GCC-11 two of the tests are faster than with clang with either cpu/arch flag:
```
v_sparse_dot ------ Value: 2.551899, Time: 494.75ns/iter
v_sparse_dot_omp -- Value: 2.551900, Time: 2318.14ns/iter
v_sparse_dot_sve -- Value: 2.551899, Time: 951.34ns/iter
```
It appears that for the function v_sparse_dot_omp the #pragma omp directives are ignored when using the Makefile as-is.
When -fopenmp is given to enable the omp options the build fails:
```
clang-15 -Wall -O3 -mcpu=neoverse-v1 -fopenmp -c -o lib.o lib.c
lib.c:35:13: error: expected an OpenMP directive
#pragma omp reduction(| : m1) reduction(| : m2)
            ^
lib.c:33:3: error: statement after '#pragma omp parallel for' must be a for loop
  while (lhs_pos < lhs_loop_len && rhs_pos < rhs_loop_len) {
  ^
2 errors generated.
make: *** [Makefile:11: lib.o] Error 1
```
The same is true with -march=armv8-a+sve.

**Comment by silver-ymz** [comment]
Thank you for pointing it out. This is my mistake. The following patch can make the compilation successful. But I don't have arm machine recently, so I can't update the benchmark results.

```diff
diff --git a/lib.c b/lib.c
index 19aa7ec..f7aff18 100644
--- a/lib.c
+++ b/lib.c
@@ -29,10 +29,10 @@ float v_sparse_dot_omp(uint32_t *lhs_idx, uint32_t *rhs_idx, float *lhs_val,
   size_t lhs_pos = 0, rhs_pos = 0, lhs_loop_len = lhs_len / chunk * chunk,
          rhs_loop_len = rhs_len / chunk * chunk;
   float buff_l[chunk], buff_r[chunk], xy = 0;
-#pragma omp parallel for reduction(+ : xy)
+#pragma omp parallel reduction(+ : xy)
   while (lhs_pos < lhs_loop_len && rhs_pos < rhs_loop_len) {
     uint8_t m1 = 0, m2 = 0;
-#pragma omp reduction(| : m1) reduction(| : m2)
+#pragma omp simd reduction(| : m1) reduction(| : m2)
     for (size_t i = 0; i < chunk; i++) {
       for (size_t j = 0; j < chunk; j++) {
         uint8_t res = lhs_idx[lhs_pos + i] == rhs_idx[rhs_pos + j];
```

**Comment by JulianMarcusSchroeder** [comment]
I focused on the sparse_dot function. GCC outputs the same code, safe for one single instruction scheduled in a different slot.
Clang, on the other hand gets creative. If I take the lib.s created by clang with `mcpu=neoverse-v1` and feed it to GCC it produces excellent results: 500ns for v_sparse_dot. If I feed the same lib.s to clang-15, I get 1700ns. Something on the IR to binary path is off. I'll get the latest clang, to make sure the issue is still there and try again. If so, I'll create an issue on the [llvm project page](https://github.com/llvm/llvm-project/issues/).

**Comment by JulianMarcusSchroeder** [comment]
Interesting: if the input data is different from run to run, the neoverse-v1 code is about 30% faster, in average,  than the armv8-a+sve code. With some data sets the armv8-a+sve code takes 4x longer than neoverse-v1 code.

**Comment by JulianMarcusSchroeder** [comment]
Updated results with appropriate input test data:
```
clang-18 -Wall -O3 -mcpu=neoverse-v1 neo-test.c neo-lib.c
./a.out 
changing matrix data for all iterations
1662ns runtime
./a.out 1
keeping matrix data for all iterations
1581ns runtime
```
versus
```
clang-18 -Wall -O3 -march=armv8.4-a+sve neo-test.c neo-lib.c
./a.out 1
keeping matrix data for all iterations
897ns runtime
./a.out 
changing matrix data for all iterations
2550ns runtime
```
Conclusion: The observed behavior is due to branch prediction. In a real use case the clang compiler produces better code with -mcpu=neoverse-v1 than with -march=armv8.4-a+sve, as one would expect.
